# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 进制转换.o acllib.o
LINKOBJ  = 进制转换.o acllib.o
LIBS     = -L"D:/Program Files/Dev-Cpp/MinGW64/lib" -L"D:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuser32.a ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libwinmm.a ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libmsimg32.a ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libkernel32.a ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libuuid.a ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libgdi32.a ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libole32.a ../../../DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/liboleaut32.a
INCS     = -I"D:/Program Files/Dev-Cpp/MinGW64/include" -I"D:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Program Files/Dev-Cpp/MinGW64/include" -I"D:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program Files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

进制转换.o: 进制转换.c
	$(CC) -c 进制转换.c -o 进制转换.o $(CFLAGS)

acllib.o: acllib.c
	$(CC) -c acllib.c -o acllib.o $(CFLAGS)
